In [1]:
import numpy as np

**Задание №1**

In [10]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]]).transpose()
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [11]:
mean_a = a.mean(axis=0) # - среднее значение по каждому признаку
mean_a

array([2. , 8.4])

**Задание №2**

In [12]:
a_centered = a - mean_a  # - находим массив центрированных признаков, вычитая соответствующее среднее из признака
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

**Задание №3**

In [16]:
a_centered_sp = np.dot(a_centered.T[0], a_centered.T[1]) # - находим сумму произведений центрированных признаков
a_centered_sp

8.0

In [17]:
print(a_centered_sp / 4) 
# - несмещенная оценка ковариации (делим сумму произведений центрированных признаков на кол-во наблюдений - 1 (наблюдений 5, значит, делим на 4))

2.0


**Задание №4**

In [21]:
cov_matrix = np.cov(a.T) # - ковариационная матрица
print(cov_matrix)
cov_matrix[0][1]  # - искомое значение ковариации(элемент в строке с индексом 0 и столбце с индексом 1)

[[1.  2. ]
 [2.  4.3]]


2.0